development:
  secret_key_base: 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa'
  devise_secret_key: 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa'

test:
  secret_key_base: 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa'
  devise_secret_key: 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa'

production:
  secret_key_base: <%= ENV['secret_key'] %>
  devise_secret_key: <%= ENV['DEVISE_SECRET_KEY'] %>
