development:
  aws_access_key: '123412341234'
  aws_secret_key: '123412341234'
  codeclimate_repo_token: '657dfa05805d9f29276d8d4aeef5a441431f1bd30e0e16454fab0ebc53d38e98'
  createsend_api_key: '123412341234'
  createsend_client_id: '123412341234'
  createsend_confirmation_email: 'example@withassociates.com'
  createsend_list_id: '123412341234'
  createsend_segment_id: '123412341234'
  devise_secret_key: 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa'
  s3_bucket_name: 'withlinks'
  secret_key_base: 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa'

test:
  aws_access_key: '123412341234'
  aws_secret_key: '123412341234'
  codeclimate_repo_token: '657dfa05805d9f29276d8d4aeef5a441431f1bd30e0e16454fab0ebc53d38e98'
  createsend_api_key: '123412341234'
  createsend_client_id: '123412341234'
  createsend_confirmation_email: 'example@withassociates.com'
  createsend_list_id: '123412341234'
  createsend_segment_id: '123412341234'
  devise_secret_key: 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa'
  s3_bucket_name: 'withlinks'
  secret_key_base: 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa'

production:
  aws_access_key: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  aws_secret_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  createsend_api_key: <%= ENV['CREATESEND_API_KEY'] %>
  createsend_client_id: <%= ENV['CREATESEND_CLIENT_ID'] %>
  createsend_confirmation_email: <%= ENV['CREATESEND_CONFIRMATION_EMAIL'] %>
  createsend_list_id: <%= ENV['CREATESEND_LIST_ID'] %>
  createsend_segment_id: <%= ENV['CREATESEND_SEGMENT_ID'] %>
  devise_secret_key: <%= ENV['DEVISE_SECRET_KEY'] %>
  s3_bucket_name: <%= ENV['S3_BUCKET_NAME'] %>
  secret_key_base: <%= ENV['secret_key'] %>
  codeclimate_repo_token: <%= ENV['CODECLIMATE_REPO_TOKEN'] %>
